server:
  port: 8081

spring:
  application:
    name: scdev4-bot
  thymeleaf:
    prefix: classpath:/templates/views/
    check-template-location: true
    suffix: .html
    mode: HTML
    cache: true
  datasource:
    url: ENC(1VlYyRLOSLyqLBZM0OqxkY+48W/cTtal3rdq/6LkbjT6ipP+I2Ls4+16Ry1AAdFTp094Oe3uq1Ow98WwzS8+kg==)
    password: ENC(wprP+yhFTSjyaIMdgHsR5Ct/oAD3CH6e)
    username: ENC(vhoYzRAAjfWlRrya46kY+g==)
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  configuration:
    default-statement-timeout: 15
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/**/*.xml

springdoc:
  api-docs:
    path: /api-docs
    version: OpenAPI_3-1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
  paths-to-match:
    - /api/v1/**

telegram:
  bot-token:
    notice: ENC(Hgv8JmqabYLTbn8xiBuFySta7VgoQYifMQ5pzNpNXNbfUVJG1bRu62JoIn5MSVv6t3pR/p1YBzc=)
    review: ENC(S+AVIJY/RUdEhkW0B0j1ZFpOuWhaM+l0bt382N7tl7OP5CTUVPmeEJxUqjKmFub7BoEqCUaFCL0=)
  chat-id:
    dev4-all: ENC(21CT4SoBbWo5JVcvvilwPSi7TLgCT2ZL)
    dev4-employee: ENC(BoADG8NnR+AMmUzys38Yp5w1RQzFZc83)
    code-review: ENC(tHlD1NsDzS6nrOB6A1ZtNaG+ImeiTBWZ)

public-data:
  api:
    key: ENC(zf+BQ6At3s/skIC8PrgsOW3iPgSV7ln2QgCTtCbxSA+DrLV02pCW7ozrCLG1TPRpUrh4BLqa2MF+/dcN/W2pzez2avanu+3wSdfBQh3LvVyNKgEGEQ8aC+qKzjydFHWA8RGSVIb1uvjHH80Gx+cONQ==)

code-review:
  target:
    branch: master