server:
  port: 8081
  servlet:
    context-path: /scdev4-bot

spring:
  application:
    name: scdev4-bot

springdoc:
  api-docs:
    path: /api-docs
    version: OpenAPI_3-1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
  paths-to-match:
    - /api/v1/**
